#!/usr/bin/env bash
#
# cmux workspace customization hook.
#
# Runs after `/cmux:new-workspace` creates an isolated worktree, before
# Claude Code launches. It generates a Docker Compose override file that
# remaps the *external* host ports of the temporal and webui services so
# this workspace does not collide with the main worktree or with other
# parallel cmux workspaces (each gets its own CMUX_PORT range).
#
# Port layout, derived from the cmux-assigned CMUX_PORT:
#   webui    HTTP UI -> ${CMUX_PORT}
#   temporal gRPC    -> ${CMUX_PORT} + 1
#   temporal Web UI  -> ${CMUX_PORT} + 2
#
# The override uses the `!override` YAML tag so it *replaces* each service's
# port list instead of concatenating to it (Compose's default merge for
# `ports` is concatenation, which would leave the original ports bound).
set -euo pipefail

if [[ -z "${CMUX_PORT:-}" ]]; then
  echo "post-create.sh: CMUX_PORT is not set; skipping compose port override." >&2
  exit 0
fi

worktree="${CMUX_FEATURE_WORKTREE:-$PWD}"
override="${worktree}/compose.override.yaml"

webui_port="${CMUX_PORT}"
temporal_grpc_port="$((CMUX_PORT + 1))"
temporal_ui_port="$((CMUX_PORT + 2))"

cat >"${override}" <<EOF
# Generated by .cmux/post-create.sh for cmux workspace "${CMUX_FEATURE_SLUG:-?}".
# Remaps external host ports off the cmux-assigned CMUX_PORT (${CMUX_PORT}) so
# parallel workspaces don't collide. Regenerated on each workspace creation;
# do not edit by hand.
services:
  temporal:
    ports: !override
      - "${temporal_grpc_port}:7233" # gRPC — workers & clients
      - "${temporal_ui_port}:8233" # Temporal Web UI
  webui:
    ports: !override
      - "${webui_port}:8000" # http — Web UI
EOF

echo "post-create.sh: wrote ${override}"
echo "  webui      http://localhost:${webui_port}"
echo "  temporal   gRPC localhost:${temporal_grpc_port}, UI http://localhost:${temporal_ui_port}"
